# ----------------------------------------------------------------------------
#
# Package             : netty-tcnative
# Source Repo         : https://github.com/netty/netty-tcnative
# Travis Job Link     : https://travis-ci.com/github/asellappen/netty-tcnative/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

sudo: True
dist: focal

arch:
  - amd64
  - ppc64le
  
 script:
  - mvn install -DskipTests=true -B -V
  - mvn test -B
